Refactor
aws/codelyzer pull request #24
Opened 2021-01-08 04:32 UTC by jonlouie

*Issue #, if available:*
https://github.com/aws/codelyzer/issues/23

*Description of changes:*
* Refactor `CSharpRoslynProcessor.cs` to DRY up repeated code and make coding patterns similar
* All unit tests pass
* **Note: PR might be easier to digest by reviewing commits individually**

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-01-08 17:30 UTC, marknfawaz requested changes

2021-01-08 18:22 UTC, jonlouie commented on src/Analysis/Codelyzer.Analysis.CSharp/CSharpRoslynProcessor.cs
> +            if (!MetaDataSettings.LiteralExpressions) return null;
Yes, that was a mistake and I will update accordingly. Will also open an issue to improve our unit tests so we detect similar missteps sooner and give confidence for future refactors.

2021-01-08 18:23 UTC, jonlouie commented on src/Analysis/Codelyzer.Analysis.CSharp/CSharpRoslynProcessor.cs
> +                        nodeList.Add(returnStatementNode);
No reason in particular. I can add identifier names along with other node types that are valid within a return statement (invocations, object creations, and literals)

2021-01-12 18:05 UTC, marknfawaz approved these changes

2021-01-12 18:06 UTC, merged