add support for argument nodes
aws/codelyzer pull request #28
Opened 2021-01-13 18:36 UTC by jonlouie

*Issue #, if available:*
https://github.com/aws/codelyzer/issues/27

*Description of changes:*
* Add support for `ArgumentSyntax` nodes
* For `InvocationExpression` and `ObjectCreationExpression` nodes, `Parameter` objects were replaced by `Argument` objects (semantically speaking, parameters are used in method declarations and arguments are used in invocations)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-01-13 18:38 UTC, jonlouie commented on .gitignore
> +
This will prevent test project files from flooding git tracking if unit testing is aborted for any reason.

2021-01-13 23:01 UTC, marknfawaz requested changes

2021-01-13 23:01 UTC, marknfawaz commented on src/Analysis/Codelyzer.Analysis.CSharp/CSharpRoslynProcessor.cs
> +                : null;
As discussed, let's try using the HandleGenericVisit here instead of maintaining a list

2021-01-14 00:20 UTC, marknfawaz requested changes

2021-01-14 00:20 UTC, marknfawaz commented on src/Analysis/Codelyzer.Analysis.CSharp/Handlers/InvocationExpressionHandler.cs
> +                Model.Arguments.Add(argument);
This might be a breaking change for other applications. We need to keep the parameter and add the argument.

2021-01-14 00:20 UTC, marknfawaz commented on src/Analysis/Codelyzer.Analysis.CSharp/Handlers/ObjectCreationExpressionHandler.cs
> +                    Model.Arguments.Add(argument);
Same comment. This change will break any applications using the parameter

2021-01-14 00:20 UTC, marknfawaz commented on src/Analysis/Codelyzer.Analysis.Model/InvocationExpression.cs
> +        public List<Argument> Arguments { get; set; }
This is an interface change. Is there a reason we can't have both?

2021-01-14 00:20 UTC, marknfawaz commented on src/Analysis/Codelyzer.Analysis.Model/InvocationExpression.cs
> +            Arguments = new List<Argument>();
Same comment. We need to keep parameters

2021-01-14 00:44 UTC, Eruanion approved these changes

2021-01-14 15:12 UTC, marknfawaz approved these changes

2021-01-14 20:42 UTC, merged