Add support for analyzing using old and new references.
aws/codelyzer pull request #67
Opened 2021-04-21 22:52 UTC by marknfawaz

## Related issue

Closes: #65
Closes: #66 

## Description
Addresses the referenced issues

## Supplemental testing
Unit testing, integration testing, and manual testing with projects

2021-04-22 01:31 UTC, jonlouie requested changes
Aside from the minor issues in the comments, my main concern is coupling codelyzer to the pre-port data structures. Since not all use cases require pre-port and post-port compilations, what are your thoughts on creating separate classes that handle dual compilation and related APIs?

2021-04-22 15:55 UTC, marknfawaz commented
> Aside from the minor issues in the comments, my main concern is coupling codelyzer to the pre-port data structures. Since not all use cases require pre-port and post-port compilations, what are your thoughts on creating separate classes that handle dual compilation and related APIs?

I think we discussed this before and I do share your concern, but decided to go this route to make sure we don't analyze a syntax tree twice and avoid code duplication. Some of these classes will need to be refactored to address this properly. However, just to clarify, we are still supporting the use cases of users analyzing without a legacy compilation.
I'm not sure I understand the separate classes suggestion, can you please clarify? Would that be two projectbuildhandlers? I will create an issue to refactor this and please feel free to provide some ideas to refactor.

2021-04-22 16:10 UTC, marknfawaz commented on src/Analysis/Codelyzer.Analysis.Build/FileBuildHandler.cs
> +                var sourceFilePath = Path.GetRelativePath(_projectPath, file);
I'm not sure which line you're referring to here. sourceFilePath is being used in the created object.

2021-04-22 16:13 UTC, marknfawaz commented on src/Analysis/Codelyzer.Analysis.Build/FileBuildHandler.cs
> +                };
Good catch. It shouldn't be null, but I added a check.

2021-04-22 17:20 UTC, jonlouie commented on src/Analysis/Codelyzer.Analysis.Build/FileBuildHandler.cs
> +                var sourceFilePath = Path.GetRelativePath(_projectPath, file);
Sorry, GitHub is showing more than what I selected. The variable `sourceFilePath` isn't being used after instantiation. Should it be used in this object creation?
```csharp
var fileResult = new SourceFileBuildResult
{
    SyntaxTree = fileTree,
    PrePortSemanticModel = PrePortCompilation?.GetSemanticModel(fileTree),
    SemanticModel = Compilation?.GetSemanticModel(fileTree),
    SourceFileFullPath = file,
    SourceFilePath = file
};
```

2021-04-22 17:54 UTC, marknfawaz commented on src/Analysis/Codelyzer.Analysis.Build/FileBuildHandler.cs
> +                var sourceFilePath = Path.GetRelativePath(_projectPath, file);
That was a bug, it should've been used in the SourceFilePath field. Just updated.

2021-04-22 18:22 UTC, jonlouie commented
> > Aside from the minor issues in the comments, my main concern is coupling codelyzer to the pre-port data structures. Since not all use cases require pre-port and post-port compilations, what are your thoughts on creating separate classes that handle dual compilation and related APIs?
> 
> I think we discussed this before and I do share your concern, but decided to go this route to make sure we don't analyze a syntax tree twice and avoid code duplication. Some of these classes will need to be refactored to address this properly. However, just to clarify, we are still supporting the use cases of users analyzing without a legacy compilation.
> I'm not sure I understand the separate classes suggestion, can you please clarify? Would that be two projectbuildhandlers? I will create an issue to refactor this and please feel free to provide some ideas to refactor.

I wanted to resurface the topic to see if there was additional thought put into this and/or if there was a plan moving forward. I did notice that codelyzer will still work for single compilation apps, but from a maintainability and readability perspective, there would ideally be separate interfaces for cases where users don't need two compilations. For example, based on the changes to `ProjectBuildHandler`, we could extract most of those changes into a child class like:
```csharp
class PortingProjectBuildHandler : ProjectBuildHandler
{
    private Compilation PrePortCompilation;
    private List<string> PrePortMetaReferences;
    private List<string> _metaReferences;
    private string _projectPath;

    public PortingProjectBuildHandler(ILogger logger, AnalyzerConfiguration analyzerConfiguration = null, List<string> metaReferences = null) 
        : base(logger, analyzerConfiguration)
    {
    	_metaReferences = metaReferences;
    }

    private List<PortableExecutableReference> LoadMetadataReferences() { ... }
    private async Task<Compilation> SetPrePortCompilation() { ... }
    public ProjectBuildResult ReferenceOnlyBuild() { ... }
    private Compilation CreateManualCompilation(string projectPath, List<string> references) { ... }
    
    private override async Task SetCompilation()
    {
        PrePortCompilation = await SetPrePortCompilation();  
        base();
    }
}
```
We could use `ProjectBuildHandler` for the usual cases and `PortingProjectBuildHandler` for the porting cases. (I'll add this example to the refactoring issue)

A similar approach can be taken for most other changes, reframing the changes such that we are extending codelyzer rather than modifying it. Doing so would prevent code duplication while isolating business logic based on use case.

2021-04-23 20:36 UTC, huawenm approved these changes

2021-04-23 20:44 UTC, jonlouie approved these changes

2021-04-23 20:58 UTC, merged